function init(self)
end

function update(self, dt)

end

function on_message(self, message_id, message, sender)

	
	
	if message_id == hash("update_score") then
		local scoreNode = gui.get_node("id_score")
		gui.set_text(scoreNode, message.score)
	end
end

function on_input(self, action_id, action)

end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
